# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0, error_messages={'blank': 'sai rui ban oi', 'no such table': 'ko co bang ghi nao ca', 'required': 'thieeu gia roi'})),
            ],
        ),
    ]
